name: System Tray Clock MSI Release Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

    steps:        
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install .net 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
          
    - name: dotnet restore
      shell: cmd
      run: dotnet restore "%Project_Path%"
    
    - name: disable out of process build for installer project
      shell: cmd
      run: |
        pushd "%VS_IDE_PATH%"
        "%VS_IDE_PATH%"\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\DisableOutOfProcBuild.exe
        popd
        
    - name: build
      timeout-minutes: 15
      continue-on-error: true
      shell: cmd
      run: |
        "%VSBUILD_PATH%" "%Solution_Name%" /Project "%Setup_Project_Path%" /Rebuild "%Configuration%"
        
    - name: upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SystemTrayClockInstaller
        path: D:\a\SystemTrayClock\SystemTrayClock\src\SystemTrayClockInstaller\Release
        
    - name: zip build artifacts
      run: |
        7z a -tzip D:\a\SystemTrayClock\SystemTrayClock\src\SystemTrayClockInstaller\Release\SystemTrayClockInstaller.zip D:\a\SystemTrayClock\SystemTrayClock\src\SystemTrayClockInstaller\Release\*.*
        
    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: ReleaseNotes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: D:\a\SystemTrayClock\SystemTrayClock\src\SystemTrayClockInstaller\Release\SystemTrayClockInstaller.zip
        asset_name: SystemTrayClockInstaller.zip
        asset_content_type: application/zip
