name: System Tray Clock MSI Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    #runs-on: windows-2019

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE
      #VSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
          
    - name: dotnet restore
      shell: cmd
      run: dotnet restore "%Project_Path%"
        
    # Build the installer
    #- name: Build the installer
    #  shell: cmd
    #  run: |
    #    "%VSBUILD_PATH%" "%Solution_Name%" /Project "%Setup_Project_Path%" /Build "%Configuration%"
    
    - name: DisableOutOfProcBuild
      shell: cmd
      run: |
        cmd /c outOfProcFix.bat "%VS_IDE_PATH%"
        
    - name: Build the installer
      shell: cmd
      run: |
        cmd /c buildInstaller.bat "%VSBUILD_PATH%" "%Solution_Name%" "%Setup_Project_Path%" "%Configuration%"

    # Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-SystemTrayClockInstaller
        path: $env:Setup_Project_Folder_Path\$env:Configuration
