name: System Tray Clock MSI Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
          
    - name: dotnet restore
      shell: cmd
      run: dotnet restore "%Project_Path%"
    
    - name: DisableOutOfProcBuild
      shell: cmd
      run: |
        START /D "%VS_IDE_PATH%"\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild "%VS_IDE_PATH%"\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\DisableOutOfProcBuild.exe 
     
    # Build the installer
    - name: Build the installer
      shell: cmd
      run: |
        START /D "%VS_IDE_PATH%" "%VSBUILD_PATH%" "%Solution_Name%" /Project "%Setup_Project_Path%" /Build "%Configuration%" > con

    # Upload the build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-SystemTrayClockInstaller
        path: $env:Setup_Project_Folder_Path\$env:Configuration
