name: System Tray Clock MSI Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
          
    - name: dotnet restore
      shell: cmd
      run: dotnet restore "%Project_Path%"
    
    - name: DisableOutOfProcBuild
      shell: cmd
      run: |
        pushd "%VS_IDE_PATH%"
        "%VS_IDE_PATH%"\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild\DisableOutOfProcBuild.exe
        popd
        
    - name: Build the installer
      timeout-minutes: 30
      shell: cmd
      run: |
        "%VSBUILD_PATH%" "%Solution_Name%" /Project "%Setup_Project_Path%" /Rebuild "%Configuration%"
        
    #- name: Build the installer
    #  shell: cmd
    #  run: |
    #    buildMonitor.bat "%VSBUILD_PATH%" "%Solution_Name%" "%Setup_Project_Path%" "%Configuration%"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: SystemTrayClockInstaller
        path: D:\a\SystemTrayClock\SystemTrayClock\src\SystemTrayClockInstaller\Release
        
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: ReleaseNotes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./SystemTrayClockInstaller.zip
        asset_name: SystemTrayClockInstaller.zip
        asset_content_type: application/zip
