name: test

on: 
  push:
    branches:
    - main
    paths:
    - 'version.txt'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

    steps:   
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: read version
      id: read_version
      run: |
        $VERSION = Get-Content D:\a\SystemTrayClock\SystemTrayClock\version.txt -Raw 
        echo $VERSION
        echo "::set-output name=VERSION::$VERSION"

    - name: show source data
      run: |
        echo ${{ steps.read_version.outputs.VERSION }}
        
