name: test

on: 
  push:
    branches:
    - main
    paths:
    - 'version.txt'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022

    env:
      Configuration: Release
      Solution_Name: SystemTrayClock.sln
      Project_Path: src\SystemTrayClock\SystemTrayClock.csproj
      Setup_Project_Path: src\SystemTrayClockInstaller\SystemTrayClockInstaller.vdproj
      Setup_Project_Folder_Path: src\SystemTrayClockInstaller\
      VSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com
      VS_IDE_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE

    steps:       
    - name: get source data
      id: branch_name
      run: |
        $SOURCE_NAME = ${env:GITHUB_REF} -replace 'refs/\w+/', ''
        $SOURCE_BRANCH = ${env:GITHUB_REF} -replace 'refs/heads/', ''
        $SOURCE_TAG = ${env:GITHUB_REF} -replace 'refs/tags/', ''
        echo "::set-output name=SOURCE_NAME::$SOURCE_NAME"
        echo "::set-output name=SOURCE_BRANCH::$SOURCE_BRANCH"
        echo "::set-output name=SOURCE_TAG::$SOURCE_TAG"
        
    - name: show source data
      run: |
        echo ${{ steps.branch_name.outputs.SOURCE_NAME }}
        echo ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        echo ${{ steps.branch_name.outputs.SOURCE_TAG }}
        
